<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="4" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[TestCase for Both Blank Credentials]]>
    </line>
  </reporter-output>
  <suite started-at="2025-01-28T16:05:02 GMT+05:45" name="Default suite" finished-at="2025-01-28T16:05:27 GMT+05:45" duration-ms="25492">
    <groups>
    </groups>
    <test started-at="2025-01-28T16:05:02 GMT+05:45" name="Default test" finished-at="2025-01-28T16:05:27 GMT+05:45" duration-ms="25492">
      <class name="com.project.zetalabs.tests.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:02 GMT+05:45" name="setup" finished-at="2025-01-28T16:05:07 GMT+05:45" duration-ms="5197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyBlankCredentials()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:07 GMT+05:45" name="verifyBlankCredentials" finished-at="2025-01-28T16:05:09 GMT+05:45" duration-ms="1811" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TestCase for Both Blank Credentials]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyBlankCredentials -->
        <test-method is-config="true" signature="closeBrowserSession(org.testng.ITestResult)[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:09 GMT+05:45" name="closeBrowserSession" finished-at="2025-01-28T16:05:09 GMT+05:45" duration-ms="333" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyBlankCredentials status=SUCCESS method=LoginTest.verifyBlankCredentials()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25] output=TestCase for Both Blank Credentials]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowserSession -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:09 GMT+05:45" name="setup" finished-at="2025-01-28T16:05:13 GMT+05:45" duration-ms="4051" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyCorrectCredentials()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:13 GMT+05:45" name="verifyCorrectCredentials" finished-at="2025-01-28T16:05:13 GMT+05:45" duration-ms="71" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.sendKeys(Unknown Source)
at com.project.zetalabs.pages.LoginPage.correctSetEmail(LoginPage.java:59)
at com.project.zetalabs.tests.LoginTest.verifyCorrectCredentials(LoginTest.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCorrectCredentials -->
        <test-method is-config="true" signature="closeBrowserSession(org.testng.ITestResult)[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:13 GMT+05:45" name="closeBrowserSession" finished-at="2025-01-28T16:05:14 GMT+05:45" duration-ms="353" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyCorrectCredentials status=FAILURE method=LoginTest.verifyCorrectCredentials()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowserSession -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:14 GMT+05:45" name="setup" finished-at="2025-01-28T16:05:18 GMT+05:45" duration-ms="4099" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyIncorrectCredentials()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:18 GMT+05:45" name="verifyIncorrectCredentials" finished-at="2025-01-28T16:05:18 GMT+05:45" duration-ms="61" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.sendKeys(Unknown Source)
at com.project.zetalabs.pages.LoginPage.incorrectSetEmail(LoginPage.java:71)
at com.project.zetalabs.tests.LoginTest.verifyIncorrectCredentials(LoginTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIncorrectCredentials -->
        <test-method is-config="true" signature="closeBrowserSession(org.testng.ITestResult)[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:18 GMT+05:45" name="closeBrowserSession" finished-at="2025-01-28T16:05:18 GMT+05:45" duration-ms="332" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyIncorrectCredentials status=FAILURE method=LoginTest.verifyIncorrectCredentials()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowserSession -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:18 GMT+05:45" name="setup" finished-at="2025-01-28T16:05:22 GMT+05:45" duration-ms="4132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyIncorrectEmail()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:22 GMT+05:45" name="verifyIncorrectEmail" finished-at="2025-01-28T16:05:22 GMT+05:45" duration-ms="54" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.sendKeys(Unknown Source)
at com.project.zetalabs.pages.LoginPage.incorrectSetEmail(LoginPage.java:71)
at com.project.zetalabs.tests.LoginTest.verifyIncorrectEmail(LoginTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIncorrectEmail -->
        <test-method is-config="true" signature="closeBrowserSession(org.testng.ITestResult)[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:22 GMT+05:45" name="closeBrowserSession" finished-at="2025-01-28T16:05:23 GMT+05:45" duration-ms="372" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyIncorrectEmail status=FAILURE method=LoginTest.verifyIncorrectEmail()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowserSession -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:23 GMT+05:45" name="setup" finished-at="2025-01-28T16:05:27 GMT+05:45" duration-ms="4006" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyIncorrectPassword()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:27 GMT+05:45" name="verifyIncorrectPassword" finished-at="2025-01-28T16:05:27 GMT+05:45" duration-ms="72" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.sendKeys(Unknown Source)
at com.project.zetalabs.pages.LoginPage.correctSetEmail(LoginPage.java:59)
at com.project.zetalabs.tests.LoginTest.verifyIncorrectPassword(LoginTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIncorrectPassword -->
        <test-method is-config="true" signature="closeBrowserSession(org.testng.ITestResult)[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25]" started-at="2025-01-28T16:05:27 GMT+05:45" name="closeBrowserSession" finished-at="2025-01-28T16:05:27 GMT+05:45" duration-ms="456" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyIncorrectPassword status=FAILURE method=LoginTest.verifyIncorrectPassword()[pri:0, instance:com.project.zetalabs.tests.LoginTest@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowserSession -->
      </class> <!-- com.project.zetalabs.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
